version: '3.8'
services:
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  api:
    container_name: "eventx-be"
    build:
      context: ./
      target: production
    image: "jackykwandesign/eventx-be"
    depends_on:
      - cache
    links:
      - cache
    environment:
      - PORT=3000
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - PRODUCT_NAME=CryptoTicker
      - NOMICS_API_KEY=${NOMICS_API_KEY}
    ports:
      - 4000:3000
    restart: always

  # frontend:
  #   container_name: "eventx-fe"
  #   build:
  #     context: ./
  #     target: production
  #   image: "jackykwandesign/eventx-fe"
  #   depends_on:
  #     - api
  #   links:
  #     - api
  #   environment:
  #     - REACT_APP_BACKEND_URL=http://host.docker.internal:3000
  #   ports:
  #     - 8080:80
  #   restart: always

volumes:
  cache:
    driver: local